
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnslkwbzqgldxsilsxre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuc2xrd2J6cWdsZHhzaWxzeHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjQyNTUsImV4cCI6MjA2NjAwMDI1NX0.iflTaZB2rC_N5inv4bc_L3Je29diM4hgsJOONYy__9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
