// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plcljsudewilftltkxtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsY2xqc3VkZXdpbGZ0bHRreHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDQzMDksImV4cCI6MjA2NDgyMDMwOX0.bSrg9i8iaKJICFhOwFF7ZTpjiuFV7onkpuP4PJmvc9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);